import type { Metadata } from "next";
import "./globals.css";
import { dmSansFont, robotoFont } from "./fonts";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFont.variable} ${dmSansFont.variable} antialiased`}
      >
        <Navbar/>
        <main className="mx-10 mt-5">
     {children}
        </main>
   
      </body>
    </html>
  );
}
